# Enable mouse support
set -g mouse on

# Use Ctrl + h/j/k/l to move between panes (Vim style)
bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R

# Use Alt + p/n to switch between windows
bind -n M-p previous-window
bind -n M-n next-window

# Enable vim copymode
set -g mode-keys vi

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Open new windows in current directory
bind c new-window -c "#{pane_current_path}"

# Remap prefix from 'C-b' to 'M-a'
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# Status bar to the top
set-option -g status-position top

# Options to make tmux more pleasant
set -g default-terminal "tmux-256color"

# Plugins (managed by TPM)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux#v2.1.3'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Enable tmux-resurrect to save and restore sessions
set -g @continuum-restore 'on'

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_number_position "right"

set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#{b:pane_current_path}"

set -g @catppuccin_window_fill "number"
set -g @catppuccin_window_text "#{b:pane_current_path}"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#{b:pane_current_path}"

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right ""
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_date_time}"
set -agF status-right ""

# Initialize TPM (keep this line at the very bottom)
run '~/.tmux/plugins/tpm/tpm'
